spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/session
    username: postgres
    password: 87654321
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.yaml
server:
  port: 8081
session:
  clean:
    enabled: true
  time: "00 00 00 * * *"
